version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites.template.${DOCKER_PROXY_NGINX_TEMPLATE:-docker}:/etc/nginx/sites.template
      - ./nginx/default/html:/var/www/html
      - ./data/log/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_DOMAIN_NAME=${DOMAIN_NAME:-wp.jesus.123it.ca}
    depends_on:
      - wordpress

    command: /bin/bash -c "envsubst '$$NGINX_DOMAIN_NAME' < /etc/nginx/sites.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    logging:
      driver: journald

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: journald

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress/html/:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    logging:
      driver: journald

  wordpress-one:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress-one
    volumes:
      - ./wordpress/one/html/:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_one
    logging:
      driver: journald

  wordpress-two:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress-two
    volumes:
      - ./wordpress/two/html/:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_two
    logging:
      driver: journald

  wordpress-standrews:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress-standrews
    volumes:
      - ./wordpress/standrews/html/:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_standrews
    logging:
      driver: journald
