version: '3.3'

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites.template.docker:/etc/nginx/sites-available/sites.template
      - ./nginx/default/html:/var/www/html
      - ./data/log/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_DOMAIN_NAME=${DOMAIN_NAME:-sahuaro.jesus.123it.ca}
    command: /bin/bash -c "envsubst '$$NGINX_DOMAIN_NAME' < /etc/nginx/sites-available/sites.template > /etc/nginx/sites-enabled/sites.conf && exec nginx -g 'daemon off;'"
    logging:
      driver: journald

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress/html/:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    logging:
      driver: journald

  wordpress-one:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-one
    volumes:
      - ./wordpress/one/html/:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_one
    logging:
      driver: journald
